version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "01:00"
    timezone: Asia/Manila
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    time: "01:00"
    timezone: Asia/Manila
