authors=David Peter <mail@david-peter.de>
categories=command-line-utilities
description=A command-line tool to generate, analyze, convert and manipulate colors
homepage=https://github.com/sharkdp/pastel
license=MIT/Apache-2.0
name=pastel
readme=README.md
repository=https://github.com/sharkdp/pastel
version=0.10.0
edition=2021
build=build.rs
exclude=doc/pastel.gif
rust-version=1.83.0
