name: Update

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - master
  #   tags:
  #     - '*'

jobs:
  update:
    name: Update Fancy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check status
      id: check_status
      shell: bash
      run: |
        chmod +x update.sh
        ./update.sh -f
        updatable=false
        [[ $(ls output | wc -l || 0) -gt 1 ]] && updatable=true
        echo "updatable=${updatable}" >> $GITHUB_OUTPUT

    - name: Tag
      if: ${{ github.env.updatable }} == "true"
      shell: bash
      run: |
        latest_tag=$(cat "build.sh" | grep -iom1 'version[ =].*' | sed 's|[^0-9.]||g')
        git tag "$latest_tag"
        git push "$latest_tag"
        
    - name: Publish
      uses: softprops/action-gh-release@v2
      if: ${{ github.env.updatable }} == "true"
      with:
        files: output/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

