name: Update

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:

jobs:
  update_fancy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run update script
        shell: bash
        run: |
          chmod +x update.sh
          ./update.sh -f